### ISSUE TITLE
Antivirus false-positive trigger

### ISSUE THREAD

**Issue by Liviu-Sorin-Rusu** [SuiMachine/AVP2PH-Custom-Launcher#5]
[https://i.imgur.com/238BEV3.png](url)

Tried launching the games simultaneous with the custom launchers.

**Comment by SuiMachine** [comment]
Possibly a result of using DLL injection (since latest builds should no longer require running as administrator, so that's one less thing to worry about). Not sure if I can do something about it... aside from rewriting the entire thing to just have a DLL wrapper.
