### ISSUE TITLE
Game will not start

### ISSUE THREAD

**Issue by TheRaggedFlag** [SuiMachine/AVP2PH-Custom-Launcher#6]
I attempt to start the game from the launcher (I have it set to run as administrator as well) and i am given an unhandled exception error (Shown below)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at AVP_CustomLauncher.mainform.stripResolutionParameters(String cmdlineparamters) in D:\Projekty\AVP2-Custom-Launcher\MainForm.cs:line 199
   at AVP_CustomLauncher.mainform.StartGame() in D:\Projekty\AVP2-Custom-Launcher\MainForm.cs:line 126
   at AVP_CustomLauncher.mainform.B_StartGame_Click(Object sender, EventArgs e) in D:\Projekty\AVP2-Custom-Launcher\MainForm.cs:line 120
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
AVP_CustomLauncher
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Fox/Aliens%20vs.%20Predator%202/AVP_CustomLauncher.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4320.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by SuiMachine** [comment]
Hmmm... that would be no command-line parameters sent to Lithtech.exe.

Interesting, cause the original launcher uses them for resolution and other stuff and so does mine, as they are required to set up stuff like window title, tell Lithtech which files to load etc. (probably also why I have never written in a check for whatever the command line contains whitespace before splitting it, as it really should have at least a dozen parameter used).

Have you maybe modified avp2cmds.txt manually? If so - maybe try deleting it, launcher should recreate it (unless it gets placed in a virtualized location by Window's UAC)

**Comment by SuiMachine** [comment]
Wait a sec. Are you using a correct launcher, even? That crash is caused by line 199, which is in Aliens vs. Predator 2 Custom Launcher, but you reported it in Aliens vs. Predator 2: Primal Hunt - Custom Launcher.

**Comment by TheRaggedFlag** [comment]
Either way, i've fixed the issue. the issue was the fact i didn't use the noCD fix, sorry for bothering you with my own mistake lol
